name: fitter-happier
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.8
  - conda-forge::numpy=1.19.2
  - conda-forge::pandas=1.1.3
  - conda-forge::scikit-learn=0.23.2
  - conda-forge::pylint=2.6.0
  - conda-forge::jupyter=1.0.0
  - conda-forge::ipykernel=5.3.4
  - conda-forge::ipdb=0.13.3
  - conda-forge::psutil=5.7.2
  - conda-forge::rtree=0.9.4
  - conda-forge::seaborn=0.11.0
  - conda-forge::pendulum=2.1.2
  - conda-forge::tqdm=4.50.2
  - conda-forge::scikit-plot=0.3.7
  - conda-forge::scikit-optimize=0.8.1
  - conda-forge::pyarrow=2.0.0
  - conda-forge::shapely=1.7.1
  - conda-forge::matplotlib=3.3.2
  - conda-forge::joblib=0.17.0
  - conda-forge::requests=2.24.0
  - conda-forge::xgboost=0.90
  - pip
  - pip:
      - tekore==3.3.0
      - opencv-python==4.4.0.44
      - urlpath==1.1.7
      - imutils==0.5.3
      - black==20.8b1
      - mgrs==1.4.0
      - pytest==5.0.1
      - pytest-cov==2.7.1
      - pytest-xdist==1.29.0
      - pytest-datafiles==2.0
